// <auto-generated />
using System;
using CyberFork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberFork.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427102843_ChangeTimeToTimestamptz")]
    partial class ChangeTimeToTimestamptz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberFork.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dishes");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_dishes_category_id");

                    b.ToTable("dishes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Томат, моцарела, базилік",
                            IsAvailable = true,
                            Name = "Піца «Маргарита»",
                            Price = 180m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Томат, моцарела, пепероні, перець чилі",
                            IsAvailable = true,
                            Name = "Піца «Пепероні»",
                            Price = 210m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Моцарела, горгонзола, пармезан, рікота",
                            IsAvailable = true,
                            Name = "Піца «Чотири сири»",
                            Price = 240m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Яловичина, чедер, салат, томат, соус BBQ",
                            IsAvailable = true,
                            Name = "CyberBurger Classic",
                            Price = 195m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Яловичина, халапеньо, чедер, соус шрірача",
                            IsAvailable = true,
                            Name = "CyberBurger Spicy",
                            Price = 215m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Краб, авокадо, огірок, ікра тобіко",
                            IsAvailable = true,
                            Name = "Рол «Каліфорнія»",
                            Price = 165m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Краб, огірок, авокадо зверху, соус унагі",
                            IsAvailable = true,
                            Name = "Рол «Дракон»",
                            Price = 195m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Вершковий сир, ванільний крем, пісочне тісто",
                            IsAvailable = true,
                            Name = "Чізкейк «Нью-Йорк»",
                            Price = 120m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Маскарпоне, савоярді, еспресо, какао",
                            IsAvailable = true,
                            Name = "Тірамісу",
                            Price = 110m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Лимон, апельсин, м'ята, газована вода",
                            IsAvailable = true,
                            Name = "Лимонад «Цитрус Mix»",
                            Price = 75m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% арабіка, подвійний шот",
                            IsAvailable = true,
                            Name = "Еспресо",
                            Price = 55m,
                            UpdatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CyberFork.Models.DishCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dish_categories");

                    b.ToTable("dish_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Класична та авторська піца з дров'яної печі",
                            Name = "Піца"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Соковиті бургери з яловичини та курки",
                            Name = "Бургери"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Свіжі роли та нігірі від шеф-кухаря",
                            Name = "Суші"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Авторські десерти та випічка",
                            Name = "Десерти"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Безалкогольні напої, коктейлі, кава",
                            Name = "Напої"
                        });
                });

            modelBuilder.Entity("CyberFork.Models.DishChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<int>("DishId")
                        .HasColumnType("integer")
                        .HasColumnName("dish_id");

                    b.HasKey("Id")
                        .HasName("pk_dish_change_logs");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_dish_change_logs_dish_id");

                    b.ToTable("dish_change_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangeDescription = "Ціну змінено з 160 на 180 грн",
                            ChangedAt = new DateTime(2024, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            ChangedBy = "admin",
                            DishId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChangeDescription = "Оновлено опис: додано соус BBQ",
                            ChangedAt = new DateTime(2024, 3, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            ChangedBy = "admin",
                            DishId = 4
                        });
                });

            modelBuilder.Entity("CyberFork.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("GuestAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("guest_address");

                    b.Property<string>("GuestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_phone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_orders_status_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Без цибулі, будь ласка",
                            CreatedAt = new DateTime(2024, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            TotalAmount = 375m,
                            UpdatedAt = new DateTime(2024, 4, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            GuestAddress = "вул. Золотоворітська, 3, Київ",
                            GuestName = "Тарас Шевченко",
                            GuestPhone = "+380991112233",
                            StatusId = 2,
                            TotalAmount = 270m,
                            UpdatedAt = new DateTime(2024, 4, 2, 12, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Доставити до 19:00",
                            CreatedAt = new DateTime(2024, 4, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 1,
                            TotalAmount = 580m,
                            UpdatedAt = new DateTime(2024, 4, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CyberFork.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer")
                        .HasColumnName("dish_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_order_items_dish_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = 1,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 180m
                        },
                        new
                        {
                            Id = 2,
                            DishId = 4,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 195m
                        },
                        new
                        {
                            Id = 3,
                            DishId = 6,
                            OrderId = 2,
                            Quantity = 1,
                            UnitPrice = 165m
                        },
                        new
                        {
                            Id = 4,
                            DishId = 7,
                            OrderId = 2,
                            Quantity = 1,
                            UnitPrice = 195m
                        },
                        new
                        {
                            Id = 5,
                            DishId = 2,
                            OrderId = 3,
                            Quantity = 2,
                            UnitPrice = 210m
                        },
                        new
                        {
                            Id = 6,
                            DishId = 5,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 215m
                        },
                        new
                        {
                            Id = 7,
                            DishId = 8,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 120m
                        });
                });

            modelBuilder.Entity("CyberFork.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_order_statuses");

                    b.ToTable("order_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Замовлення щойно створено",
                            Name = "Нове"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Кухня приступила до приготування",
                            Name = "Готується"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Замовлення передано кур'єру",
                            Name = "Доставляється"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Замовлення успішно доставлено",
                            Name = "Виконано"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Замовлення скасовано",
                            Name = "Скасовано"
                        });
                });

            modelBuilder.Entity("CyberFork.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cyberfork.ua",
                            Name = "Адміністратор",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Phone = "+380501234567",
                            Role = "admin",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "вул. Хрещатик, 1, Київ",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "olena@example.com",
                            Name = "Олена Коваль",
                            PasswordHash = "e606e38b0d8c19b24cf0ee3808183162ea7cd63ff7912dbb22b5e803286b4446",
                            Phone = "+380671234567",
                            Role = "user",
                            UpdatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "вул. Сагайдачного, 5, Київ",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mykhailo@example.com",
                            Name = "Михайло Бондаренко",
                            PasswordHash = "e606e38b0d8c19b24cf0ee3808183162ea7cd63ff7912dbb22b5e803286b4446",
                            Phone = "+380631234567",
                            Role = "user",
                            UpdatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CyberFork.Models.Dish", b =>
                {
                    b.HasOne("CyberFork.Models.DishCategory", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dishes_dish_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CyberFork.Models.DishChangeLog", b =>
                {
                    b.HasOne("CyberFork.Models.Dish", "Dish")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dish_change_logs_dishes_dish_id");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("CyberFork.Models.Order", b =>
                {
                    b.HasOne("CyberFork.Models.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_statuses_status_id");

                    b.HasOne("CyberFork.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberFork.Models.OrderItem", b =>
                {
                    b.HasOne("CyberFork.Models.Dish", "Dish")
                        .WithMany("OrderItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_dishes_dish_id");

                    b.HasOne("CyberFork.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CyberFork.Models.Dish", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CyberFork.Models.DishCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("CyberFork.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CyberFork.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CyberFork.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
